#ifndef FLASH_LAYOUT_H
#define FLASH_LAYOUT_H

#include <stdint.h>

typedef struct
{
    uint32_t start;
    uint32_t end;
    uint32_t size;
} FlashRegion_t;

#define FLASH_MEMORY_START       0x08000000U
#define FLASH_MEMORY_END         0x08020000U

#define FLASH_BOOTLOADER_START   FLASH_MEMORY_START
#define FLASH_BOOTLOADER_END     0x08007800U

#define FLASH_METADATA_START     0x08007800U
#define FLASH_METADATA_END       0x08008000U

#define FLASH_APP_HEADER_START   0x08008000U
#define FLASH_APP_HEADER_END     0x08008800U

#define FLASH_APPLICATION_START  0x08008800U
#define FLASH_APPLICATION_END    FLASH_MEMORY_END

#define FLASH_METADATA_SIZE      (FLASH_METADATA_END - FLASH_METADATA_START)
#define FLASH_APP_HEADER_SIZE    (FLASH_APP_HEADER_END - FLASH_APP_HEADER_START)
#define FLASH_APPLICATION_SIZE   (FLASH_APPLICATION_END - FLASH_APPLICATION_START)

#endif